[2023-06-30T13:31:48.369+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: UpdateSymbol.get_historical_prices scheduled__2023-06-29T10:00:00+00:00 [queued]>
[2023-06-30T13:31:48.375+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: UpdateSymbol.get_historical_prices scheduled__2023-06-29T10:00:00+00:00 [queued]>
[2023-06-30T13:31:48.375+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-06-30T13:31:48.375+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-06-30T13:31:48.375+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-06-30T13:31:48.383+0000] {taskinstance.py:1300} INFO - Executing <Task(_PythonDecoratedOperator): get_historical_prices> on 2023-06-29 10:00:00+00:00
[2023-06-30T13:31:48.387+0000] {standard_task_runner.py:55} INFO - Started process 86 to run task
[2023-06-30T13:31:48.389+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'UpdateSymbol', 'get_historical_prices', 'scheduled__2023-06-29T10:00:00+00:00', '--job-id', '135', '--raw', '--subdir', 'DAGS_FOLDER/UpdateSymbol.py', '--cfg-path', '/tmp/tmp_02l1lcw']
[2023-06-30T13:31:48.390+0000] {standard_task_runner.py:83} INFO - Job 135: Subtask get_historical_prices
[2023-06-30T13:31:48.427+0000] {task_command.py:388} INFO - Running <TaskInstance: UpdateSymbol.get_historical_prices scheduled__2023-06-29T10:00:00+00:00 [running]> on host 3e27a434ea90
[2023-06-30T13:31:48.469+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=UpdateSymbol
AIRFLOW_CTX_TASK_ID=get_historical_prices
AIRFLOW_CTX_EXECUTION_DATE=2023-06-29T10:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-06-29T10:00:00+00:00
[2023-06-30T13:31:48.796+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 217, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/UpdateSymbol.py", line 22, in get_historical_prices
    data = ticket.history()
  File "/home/airflow/.local/lib/python3.7/site-packages/yfinance/utils.py", line 105, in wrapper
    result = func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/yfinance/base.py", line 199, in history
    tz = self._get_ticker_tz(proxy, timeout)
  File "/home/airflow/.local/lib/python3.7/site-packages/yfinance/base.py", line 1422, in _get_ticker_tz
    cache.store(self.ticker, tz)
  File "/home/airflow/.local/lib/python3.7/site-packages/yfinance/utils.py", line 984, in store
    raise Exception("Tkr {} tz already in cache".format(tkr))
Exception: Tkr AAPL tz already in cache
[2023-06-30T13:31:48.808+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=UpdateSymbol, task_id=get_historical_prices, execution_date=20230629T100000, start_date=20230630T133148, end_date=20230630T133148
[2023-06-30T13:31:48.821+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 135 for task get_historical_prices (Tkr AAPL tz already in cache; 86)
[2023-06-30T13:31:48.842+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-06-30T13:31:48.858+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
